### ISSUE TITLE
Update footer logos with the FSE logo

### ISSUE THREAD

**Issue by sandroscosta** [fccn/nau-richie-site-factory#190]
The footer logos are not correct, as we have funding coming from the Fundo Social Europeu, or FSE.
This new logo has to be included after the FEDER one.

Ideally, take advantage of this switch and improve reading of the current logos.

**Comment by igobranco** [comment]
I've updated the footer logos in production on www.nau.edu.pt.
They haven't updated on not authenticated pages, but it should be related to internal Django CMS cache.
I've removed the link where each image was put. And used the new Generic Image component that already also includes the Link component. This as increased the image size automatically!! That was another problema that we had.

![image](https://github.com/fccn/nau-richie-site-factory/assets/67018/76971729-e602-41a1-b8f8-2873a62638f3)
