### ISSUE TITLE
Subscribe newsletter page with a video play icon

### ISSUE THREAD

**Issue by igobranco** [fccn/nau-richie-site-factory#196]
When we change the video player to be lazy and add a additional step so we don't load the iframe even the user don't want to play the video #157 #167, this new feature had the impact of the "Subscribe to newsletter" page is using the video player component to iframe the e-goi.

https://www.nau.edu.pt/en/newsletter/

![image](https://github.com/fccn/nau-richie-site-factory/assets/67018/cf9496ac-741f-414d-862a-b445b52cb189)

**Comment by sandroscosta** [comment]
After an initial analysis, I propose 2 solutions to this issue:

* Have a flag on `video_player_plugin` to disable the playbutton;
* Create a new `embeddable_plugin` to allow the placement of external contents. This would apply directly to this situation and wouldn't change or create complex behaviour on the `video_player_plugin`.

Last, but not least, there's a https://github.com/django-cms/djangocms-snippet that we can use to place HTML/JS blocks on the site.

**Comment by igobranco** [comment]
I think we should use the 2nd option. We should separate the videos from the HTML/JS blocks.
I think we should test the installation of the plugin djangocms-snippet on this repository.

**Comment by sandroscosta** [comment]
I'll test out the `djangocms-snippet`.

**Comment by sandroscosta** [comment]
`djangocms_snippet` works as intended and solves the issue.
Will push a PR to install it on `nau-site-factory`

**Comment by igobranco** [comment]
Snippet that we should configure:

```html
<iframe
    title="Newsletter NAU"
    src="https://mkt.nau.edu.pt/w/nereT0Sech5wqfQLy44e1920803de!uid"
    allowfullscreen=""
    style="width: 100%; height: 20rem;"
    frameBorder="0">
</iframe>
```

**Comment by igobranco** [comment]
Changed in production! https://www.nau.edu.pt/pt/newsletter/
