### ISSUE TITLE
Upgrade Richie to 2.26.0

### ISSUE THREAD

**Issue by sandroscosta** [fccn/nau-richie-site-factory#240]
Upgrade Richie to the latest version to upgrade Django CMS.

https://github.com/openfun/richie/blob/master/UPGRADE.md

**Comment by igobranco** [comment]
Double check this old PR: https://github.com/fccn/nau-richie-site-factory/pull/202

**Comment by sandroscosta** [comment]
FUN Replaced the ubuntu base image for running CircleCI with
`  - image: cimg/base:current`
We currently have `cimg/base:2022.06`

**Comment by sandroscosta** [comment]
Need to fix spacing for 

![Image](https://github.com/fccn/nau-richie-site-factory/assets/34194007/99014701-1031-4abf-b46e-e580dce8e661)

After the upgrade, the containers ended up weirdly proportioned
