### ISSUE TITLE
Upgrade NAU site to use Node 20

### ISSUE THREAD

**Issue by igobranco** [fccn/nau-richie-site-factory#244]
The Richie cookiecutter is using node 20, on the NAU upgrade we have been forgetting to upgrade the cookiecutter site factory.

This isn't easy because we have custom code, but we should make a best effort to compare our project with current recommended values of Richie cookiecutter.

https://github.com/openfun/richie/commit/1fbb728b937782ae873fe1fab5a72ea5ca297cef#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47

**Comment by igobranco** [comment]
Old PR to https://github.com/fccn/nau-richie-site-factory/pull/202

**Comment by sandroscosta** [comment]
Upgraded Node and Python version for the latest version of Richie.
