### ISSUE TITLE
Upgrade richie to v2.29.1 on nau-richie-site-factory

### ISSUE THREAD

**Issue by igobranco** [fccn/nau-richie-site-factory#261]
https://github.com/openfun/richie/releases

**Comment by sandroscosta** [comment]
@Tiago-Salles I still have this open. How is this going? Should we close this and create a new one?

**Comment by Tiago-Salles** [comment]
@sandroscosta  I just talked with @igobranco, I will update the version as now the latest is `v2.31.0`

**Comment by Tiago-Salles** [comment]
It no longer has sense as we will update to `v2.31`.
